### PR TITLE
completed!

### PR DESCRIPTION
**Pull request by Varaaaaaaa**

### CODE REVIEW

**Review by DRK-20 — CHANGES_REQUESTED** [review]
Upload the txt file and your dataset in a folder with your name and then submit

**Comment by Varaaaaaaa** [comment]
done

**Comment by Varaaaaaaa** [comment]
done!

**Review by DRK-20 — CHANGES_REQUESTED** [review]
more data visualization required

**Comment by Varaaaaaaa** [comment]
DONE!!!!

**Pull request closed without merging**
